{
 "title": "Global Quantum Gateway Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "![Image](https://www.e92plus.com/img/logos/vendors/trustwave_logo_white.png)\n\n\n"
   },
   "content": "![Image](https://www.e92plus.com/img/logos/vendors/trustwave_logo_white.png)\n\n\n"
  },
  {
   "title": "Connected Gateway List",
   "type": "dashlist",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 19, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Dashboard Exception List", "type": "alertlist", "gridPos": { "h": 17, "w": 10, "x": 0, "y": 7 } },
  {
   "type": "aidanmountford-html-panel",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 19 },
   "format": "short",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "aidanmountford-html-panel",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 19 },
   "format": "short",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gateway[00] work load panel",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 23 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Gateway_00",
     "select": [
      [
       { "params": [ "ival" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "oval" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gateway [01] work load panel",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 23 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Gateway_00",
     "select": [
      [
       { "params": [ "ival" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "oval" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Deployed Gateway Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 24 },
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "location",
     "select": [
      [
       { "params": [ "longitude" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "latitude" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "yesoreyeram-boomtheme-panel",
   "gridPos": { "h": 2, "w": 14, "x": 10, "y": 29 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}